### ISSUE TITLE
Sample file

### ISSUE THREAD

**Issue by Alexey-T** [jims/sublime-sjson#1]
Hi. Wanted to see sample files, several,of SJSON. Do you have such? Can you share em to test syntax?

**Comment by jims** [comment]
Yeah sure, here you go: https://gist.github.com/jims/c7034bbce646fc6ff662

Theres a couple of bugs in the syntax in this plugin that have been fixed in https://github.com/jims/atom-stingray/blob/master/grammars/sjson.cson

**Comment by Alexey-T** [comment]
Ok.
